# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encontrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 449)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 64, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 40, 90, 17))
        self.label_2.setObjectName("label_2")
        self.input_caminho = QtWidgets.QLineEdit(self.centralwidget)
        self.input_caminho.setGeometry(QtCore.QRect(105, 9, 311, 25))
        self.input_caminho.setObjectName("input_caminho")
        self.input_procurar = QtWidgets.QLineEdit(self.centralwidget)
        self.input_procurar.setGeometry(QtCore.QRect(105, 40, 311, 25))
        self.input_procurar.setObjectName("input_procurar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(9, 71, 230, 17))
        self.label_3.setObjectName("label_3")
        self.btn_procurar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_procurar.setGeometry(QtCore.QRect(440, 10, 80, 61))
        self.btn_procurar.setObjectName("btn_procurar")
        self.tela = QtWidgets.QScrollArea(self.centralwidget)
        self.tela.setGeometry(QtCore.QRect(9, 100, 511, 321))
        self.tela.setWidgetResizable(True)
        self.tela.setObjectName("tela")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tela.setWidget(self.scrollAreaWidgetContents)
        self.contagem = QtWidgets.QLabel(self.centralwidget)
        self.contagem.setGeometry(QtCore.QRect(240, 70, 31, 21))
        self.contagem.setText("")
        self.contagem.setObjectName("contagem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buscador"))
        self.label.setText(_translate("MainWindow", "Caminho:"))
        self.label_2.setText(_translate("MainWindow", "Procurar por:"))
        self.label_3.setText(_translate("MainWindow", "Numero de arquivos encontrados:"))
        self.btn_procurar.setText(_translate("MainWindow", "Procurar"))
