# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPF.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 98)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.input_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cpf.setGeometry(QtCore.QRect(140, 10, 321, 30))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(12)
        self.input_cpf.setFont(font)
        self.input_cpf.setObjectName("input_cpf")
        self.btn_gerar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gerar.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(12)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setStyleSheet("")
        self.btn_gerar.setObjectName("btn_gerar")
        self.btn_validar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_validar.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(12)
        self.btn_validar.setFont(font)
        self.btn_validar.setStyleSheet("")
        self.btn_validar.setObjectName("btn_validar")
        self.label_retorno = QtWidgets.QLabel(self.centralwidget)
        self.label_retorno.setGeometry(QtCore.QRect(140, 50, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_retorno.setFont(font)
        self.label_retorno.setStyleSheet("")
        self.label_retorno.setText("")
        self.label_retorno.setAlignment(QtCore.Qt.AlignCenter)
        self.label_retorno.setObjectName("label_retorno")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validar e Gerar CPF"))
        self.btn_gerar.setText(_translate("MainWindow", "GERAR"))
        self.btn_validar.setText(_translate("MainWindow", "VALIDAR"))
